### ISSUE TITLE
barman prom-exporter: configurable http port

### ISSUE THREAD

**Issue by lhoss** [DECSIS/docker-barman#17]
Port is currently hardcoded (to 8000)
I want to contribute an improvment to have it configurable (keeping old port as default) through 1 of the following ways:
* (opt) cmd-line args (like `--listen-port`)
* new (opt) ENV var like `BARMAN_EXPORTER_PORT`
  * PR (for this variant): https://github.com/DECSIS/docker-barman/pull/18

any preference @rsilva4 ?  
IMO using the ENV is easier and consistent to the current impl.  though using cmdline args would be more standard

**Comment by rsilva4** [comment]
I prefer ENV and I have just accepted your PR for that reason. I don't have anything against the cmd-line option but as you said is easier and consistent with the current impl. If you wish to add it as an alternative go for it.
