### ISSUE TITLE
Always ask root@rec_pg password

### ISSUE THREAD

**Issue by today4king** [DECSIS/docker-barman#22]
Use example docker compose up ,but failed at backup all step.
its always ask root@rec_pg password
still failed after volumen .ssh folder that i can ssh inside the barman container

**Comment by imadassamani** [comment]
The ssh command is automatically run from the /scripts/post_backup.sh. This ssh is actually for restoring in another DB, so you can actually exclude this script. But the same thing still happens even if you manually run the restore command. Just enter the correct password. After a certain number of times, it will restore successfully. My assumption is some of the action requires password to do, but not sure why it's still needed even after ssh-ing
