### ISSUE TITLE
Remote database

### ISSUE THREAD

**Issue by tarasinf** [DECSIS/docker-barman#23]
How to use with a remote database?

**Comment by rsilva4** [comment]
The image does not limit the use to local servers. Be aware that you have to properly configure the server to allow connections via TCP to the user(s) you are configuring (`pg_hba.conf`) and also that PostgreSQL by default only listens to local interfaces and you may have to adjust the corresponding setting (`listen_addresses` in `postgresql.conf`).

This [link](https://blog.bigbinary.com/2016/01/23/configure-postgresql-to-allow-remote-connection.html) contains a small tutorial on that matter.

**Comment by tarasinf** [comment]
@rsilva4 thanks. 
It would be great to add some info about it to docs.
