### ISSUE TITLE
Lock files are not deleted when docker container is stopped

### ISSUE THREAD

**Issue by alhafoudh** [DECSIS/docker-barman#8]
When I stop docker barman container, lock files are not cleared

```
-rw------- 1 lxd  lxd     4 Apr  4 13:43 .postgresql.postgresql.rancher.internal-archive-wal.lock
-rw------- 1 lxd  lxd     4 Apr  4 13:43 .postgresql.postgresql.rancher.internal-cron.lock
-rw------- 1 lxd  lxd     4 Apr  4 13:29 .postgresql.postgresql.rancher.internal-receive-wal.lock
-rw------- 1 lxd  lxd     4 Apr  4 13:43 .postgresql.postgresql.rancher.internal-xlogdb.lock
```

**Comment by alhafoudh** [comment]
Wow! Thanks

**Comment by alhafoudh** [comment]
Can you please also make a release so there is latest image available on docker hub?

**Comment by rsilva4** [comment]
@alhafoudh sure, I'm testing the `latest` tag against my production environment and I just catch #11 which is still being built:

![image](https://cloud.githubusercontent.com/assets/374537/24664487/b56094c4-1952-11e7-9404-e6dc0939d3e9.png)

Afterwards, if all looks good, a new tagged release will be available. I will be switching to a branch based image testing strategy so `latest` is always as stable as possible.

**Comment by alhafoudh** [comment]
Great, thanks

**Comment by rsilva4** [comment]
Done v0.9.2. Did you fin the image useful? Feel free to share your feedback and suggestions.

**Comment by alhafoudh** [comment]
Yes, I just upgraded. I am building the environment right now, so I will see in production how it goes. I used WAL-E until now.
